Add logDirectory option to copy logs to WACZ
harvard-lil/js-wacz pull request #119
Opened 2024-08-13 20:05 UTC by tw4l

Fixes #118 

Thanks for taking a look, this is one of the last things needed for Browsertrix Crawler!

2024-08-15 21:04 UTC, matteocargnelutti requested changes
@tw4l This looks great as usual 🤝 ! 

One question and one request: 
- Is there a common pattern for these log files (extension, content, etc ...)? I would be interested in making that feature less permissive, so that we don't have a "add whatever to WACZ" flag 😅 . 
- Would you mind adding docs for this new option to `types.js` so the IDE / JSDoc knows about this new option? 

Thank you!

2024-08-15 21:09 UTC, tw4l commented
>     * Is there a common pattern for these log files (extension, content, etc ...)? I would be interested in making that feature less permissive, so that we don't have a "add whatever to WACZ" flag 😅 .

The log files from Browsertrix Crawler are JSON-L files with `.log` as the extension - happy to add extra validation there. Perhaps we can limit to `log` or `txt` extensions for now? I think if there was an issue with the correctness of the log files (not that I've seen that happen, but you never know) it'd still be better to include a file with a formatting issue rather than no logs.

>     * Would you mind adding docs for this new option to `types.js` so the IDE / JSDoc knows about this new option?

Happy to!

2024-08-15 21:26 UTC, matteocargnelutti commented
@tw4l 
> The log files from Browsertrix Crawler are JSON-L files with .log as the extension - happy to add extra validation there. Perhaps we can limit to log or txt extensions for now? I think if there was an issue with the correctness of the log files (not that I've seen that happen, but you never know) it'd still be better to include a file with a formatting issue rather than no logs.

That makes sense. Let's start by only accepting `.log` and `.txt` files. Thank you :)

2024-08-16 11:42 UTC, tw4l commented on index.js
> +  logDirectory = null
Done! I kept the option for class initialization as `logDirectory` and CLI flag as log-directory for compatibility with py-wacz but internally it now uses `this.logDir`

2024-08-16 11:46 UTC, tw4l commented on index.js
> +  logDirectory = null
Feel free to change the former though, I don't have a strong opinion, as long as the CLI flag is the same I think we're good :)

2024-08-16 11:47 UTC, tw4l commented
Rebased and updated, thanks!

2024-08-19 15:41 UTC, matteocargnelutti commented
Hey there @tw4l! This is great, thanks! 
I pushed a commit for suggest an updated naming convention for all options that expect / accept a path to dir - what do you think? 

Cheers,

2024-08-26 14:59 UTC, tw4l commented
> Hey there @tw4l! This is great, thanks! I pushed a commit to suggest an updated naming convention for all options that expect / accept a path to dir - what do you think?

Hi @matteocargnelutti , makes sense to me! The consistency is nice :) Thanks for this!

2024-08-27 19:15 UTC, matteocargnelutti approved these changes

2024-08-28 15:48 UTC, merged